name: devops pipeline
on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: node environment
          uses: actions/setup-node@v3
            with:
              node-version: "16"
        - run: cd backend && npm install


