name: devops pipeline
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Run unit and integration tests
        run: | 
          cd backend && 
          npm install && 
          npm run test
      - name: Run e2e tests
        run: |
          cd backend &&
          (npm run start &) && 
          cd ../frontend && 
          npm install && 
          (npm run serve &) && 
          npm run test:e2e



